
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                Interpretação = @"Eu gosto do professor",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Opinião with predicted Opinião from sample data...\n\n");


            Console.WriteLine($"Interpretação: {@"Eu gosto do professor"}");
            Console.WriteLine($"Opinião: {@"Opinião positiva"}");


            Console.WriteLine($"\n\nPredicted Opinião: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
